# 生产环境配置
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:fruit_pieces_favorites}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
    # 生产环境连接池配置
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
      web-stat-filter:
        enabled: false  # 生产环境关闭Web监控
      stat-view-servlet:
        enabled: false  # 生产环境关闭监控页面
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

# 日志配置
logging:
  level:
    root: INFO
    com.fruitpieces.favorites: INFO
    org.springframework.web: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: /var/log/fruit-pieces-favorites/application.log
    max-size: 200MB
    max-history: 60
  logback:
    rollingpolicy:
      max-file-size: 200MB
      total-size-cap: 5GB

# 禁用Knife4j
knife4j:
  enable: false

# 应用监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true

# 微信小程序配置
wechat:
  miniapp:
    app-id: ${WECHAT_APP_ID}
    app-secret: ${WECHAT_APP_SECRET}

# 应用自定义配置
app:
  # JWT配置
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000  # 24小时
    refresh-expiration: 604800000  # 7天
  
  # 链接解析配置
  link-parser:
    timeout: 15000
    retry-times: 3
    user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15
  
  # 缓存配置
  cache:
    default-ttl: 7200  # 2小时
    link-info-ttl: 86400  # 24小时
    user-info-ttl: 3600  # 1小时
  
  # 文件上传配置
  upload:
    max-file-size: 5MB
    upload-path: ${UPLOAD_PATH:/data/uploads/}